<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>
<center><b><h1>Kanasagara Het (206)</b></center>    
<center><b><h1>Lab - 2</b></center>    
<pre>

# Exploratory Data Analysis (EDA) Of vehicle insurance fraud detection

In [1]:
import pandas as pd
df = pd.read_csv("insurance_fraud_data.csv")
df

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.21104,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N

# 1. Dataset Overview

Dataset Overview is the first step in **Exploratory Data Analysis (EDA)**. It provides a quick understanding of the dataset's structure, size, and features before performing further analysis.

### Questions

1. What is the shape of the dataset?
2. How many rows are there?
3. How many columns are there?
4. What is the data type of each column?
5. Print the name of all the columns.

In [2]:
df.shape

(12002, 29)

In [3]:
df.shape[0]

12002

In [4]:
df.shape[1]

29

In [5]:
df.dtypes

claim_number            int64
age_of_driver           int64
gender                 object
marital_status         object
safety_rating           int64
annual_income         float64
high_education          int64
address_change          int64
property_status        object
zip_code                int64
claim_date             object
claim_day_of_week      object
accident_site          object
past_num_of_claims      int64
witness_present        object
liab_prct               int64
channel                object
police_report           int64
age_of_vehicle         object
vehicle_category       object
vehicle_price         float64
vehicle_color          object
total_claim           float64
injury_claim           object
policy deductible       int64
annual premium        float64
days open             float64
form defects            int64
fraud reported         object
dtype: object

In [6]:
df.columns

Index(['claim_number', 'age_of_driver', 'gender', 'marital_status',
       'safety_rating', 'annual_income', 'high_education', 'address_change',
       'property_status', 'zip_code', 'claim_date', 'claim_day_of_week',
       'accident_site', 'past_num_of_claims', 'witness_present', 'liab_prct',
       'channel', 'police_report', 'age_of_vehicle', 'vehicle_category',
       'vehicle_price', 'vehicle_color', 'total_claim', 'injury_claim',
       'policy deductible', 'annual premium', 'days open', 'form defects',
       'fraud reported'],
      dtype='object')

# 2. DataFrame Summary

A **DataFrame Summary** provides a statistical overview of the dataset. It helps you quickly understand the distribution, central tendency, spread, and count of values in numerical columns. You can summarize the entire DataFrame or focus on specific columns based on your analysis needs.

### Questions

1. Summarize the entire DataFrame.
2. Summarize all the columns.
3. Summarize any one particular column.
4. Summarize any two or more columns at once.

In [7]:
df.describe()

,claim_number,age_of_driver,safety_rating,annual_income,high_education,address_change,zip_code,past_num_of_claims,liab_prct,police_report,vehicle_price,total_claim,policy deductible,annual premium,days open,form defects
count,1.200200e+04,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000
mean,3.119801e+08,43.525162,73.702966,63658.226534,0.698134,0.576737,49762.387269,0.494918,49.770122,0.601066,22925.335594,22861.534958,1011.039827,1268.140663,8.799198,3.969588
std,1.795997e+08,12.201298,15.378967,17289.704559,0.459087,0.494097,29133.180765,0.956002,33.581191,0.489699,12108.888412,12197.334761,562.099581,231.670671,2.413533,1.986915
min,1.866240e+05,19.000000,2.000000,-1.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2261.507903,2583.428985,500.000000,433.330000,2.303305,0.000000
25%,1.561887e+08,35.000000,66.000000,56899.200000,0.000000,0.000000,20111.000000,0.000000,18.000000,0.000000,14087.559950,13832.784382,500.000000,1082.360000,8.025550,3.000000
50%,3.121908e+08,43.000000,76.000000,60899.200000,1.000000,1.000000,50027.000000,0.000000,50.000000,1.000000,20642.029325,20508.293695,1000.000000,1239.060000,9.268787,4.000000
75%,4.677938e+08,51.000000,85.000000,64697.600000,1.000000,1.000000,80036.750000,1.000000,82.000000,1.000000,29293.641235,29205.553660,1000.000000,1383.490000,10.307928,5.000000
max,6.220385e+08,278.000000,100.000000,257313.600000,1.000000,1.000000,85083.000000,6.000000,100.000000,1.000000,106991.684500,101818.964200,2000.000000,2047.590000,15.177169,13.000000

In [8]:
df.describe(include="all")

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
count,1.200200e+04,12002.000000,12002,12002,12002.000000,12002.000000,12002.000000,12002.000000,12002,12002.000000,...,12002,12002.000000,12002,12002.000000,12002,12002.000000,12002.000000,12002.000000,12002.000000,11994
unique,NaN,NaN,2,3,NaN,NaN,NaN,NaN,2,NaN,...,3,NaN,7,NaN,11989,NaN,NaN,NaN,NaN,2
top,NaN,NaN,M,1,NaN,NaN,NaN,NaN,Own,NaN,...,Compact,NaN,red,NaN,*,NaN,NaN,NaN,NaN,N
freq,NaN,NaN,6216,8582,NaN,NaN,NaN,NaN,6639,NaN,...,4033,NaN,1766,NaN,14,NaN,NaN,NaN,NaN,9043
mean,3.119801e+08,43.525162,NaN,NaN,73.702966,63658.226534,0.698134,0.576737,NaN,49762.387269,...,NaN,22925.335594,NaN,22861.534958,NaN,1011.039827,1268.140663,8.799198,3.969588,NaN
std,1.795997e+08,12.201298,NaN,NaN,15.378967,17289.704559,0.459087,0.494097,NaN,29133.180765,...,NaN,12108.888412,NaN,12197.334761,NaN,562.099581,231.670671,2.413533,1.986915,NaN
min,1.866240e+05,19.000000,NaN,NaN,2.000000,-1.600000,0.000000,0.000000,NaN,0.000000,...,NaN,2261.507903,NaN,2583.428985,NaN,500.000000,433.330000,2.303305,0.000000,NaN
25%,1.561887e+08,35.000000,NaN,NaN,66.000000,56899.200000,0.000000,0.000000,NaN,20111.000000,...,NaN,14087.559950,NaN,13832.784382,NaN,500.000000,1082.360000,8.025550,3.000000,NaN
50%,3.121908e+08,43.000000,NaN,NaN,76.000000,60899.200000,1.000000,1.000000,NaN,50027.000000,...,NaN,20642.029325,NaN,20508.293695,NaN,1000.000000,1239.060000,9.268787,4.000000,NaN
75%,4.677938e+08,51.000000,NaN,NaN,85.000000,64697.600000,1.000000,1.000000,NaN,80036.750000,...,NaN,29293.641235,NaN,29205.553660,NaN,1000.000000,1383.490000,10.307928,5.000000,NaN
max,6.220385e+08,278.000000,NaN,NaN,100.000000,257313.600000,1.000000,1.000000,NaN,85083.000000,...,NaN,106991.684500,NaN,101818.964200,NaN,2000.000000,2047.590000,15.177169,13.000000,NaN

In [9]:
df["vehicle_price"].describe()

count     12002.000000
mean      22925.335594
std       12108.888412
min        2261.507903
25%       14087.559950
50%       20642.029325
75%       29293.641235
max      106991.684500
Name: vehicle_price, dtype: float64

In [10]:
df[["vehicle_category" , "vehicle_price" , "vehicle_color"]].describe(include="all")

       vehicle_category  vehicle_price vehicle_color
count             12002   12002.000000         12002
unique                3            NaN             7
top             Compact            NaN           red
freq               4033            NaN          1766
mean                NaN   22925.335594           NaN
std                 NaN   12108.888412           NaN
min                 NaN    2261.507903           NaN
25%                 NaN   14087.559950           NaN
50%                 NaN   20642.029325           NaN
75%                 NaN   29293.641235           NaN
max                 NaN  106991.684500           NaN

# 3. Selecting Columns

Selecting columns allows you to extract one or more specific columns from a DataFrame for analysis. This helps you focus only on the relevant data instead of working with the entire dataset.

### Questions

1. Select and display the **`age_of_driver`** column.
2. Select and display the **`vehicle_category`**, **`vehicle_price`**, and **`vehicle_color`** columns.
3. Select the **`vehicle_category`**, **`vehicle_price`**, and **`vehicle_color`** columns, and display only the **last 10 records**.
4. Store the **`annual_income`** column as a Pandas **Series** named **`yearly_income`**, and print its data type.

In [11]:
df["age_of_driver"]

0        39
1        33
2        31
3        53
4        41
         ..
11997    34
11998    65
11999    64
12000    34
12001    45
Name: age_of_driver, Length: 12002, dtype: int64

In [12]:
df[["vehicle_category" , "vehicle_price" , "vehicle_color"]]

      vehicle_category  vehicle_price vehicle_color
0                Large   24360.592730        silver
1               Medium   23457.352820         black
2               Medium   19752.425230          gray
3               Medium   32910.342240           red
4               Medium   28570.376750           red
...                ...            ...           ...
11997            Large   24134.334750           red
11998          Compact   57417.739270          gray
11999            Large   20231.723630         other
12000          Compact   21900.031920         black
12001           Medium    8291.858346           red

[12002 rows x 3 columns]

In [13]:
df[["vehicle_category" , "vehicle_price" , "vehicle_color"]].tail(10)

      vehicle_category  vehicle_price vehicle_color
11992          Compact   13391.566810          gray
11993           Medium    6625.618162         black
11994           Medium   20732.814060          gray
11995            Large   50804.103420          gray
11996          Compact   43472.514050         white
11997            Large   24134.334750           red
11998          Compact   57417.739270          gray
11999            Large   20231.723630         other
12000          Compact   21900.031920         black
12001           Medium    8291.858346           red

In [14]:
yearly_income = df["annual_income"]
yearly_income

0        58612.8
1        35936.0
2        84940.8
3        73526.4
4        59403.2
          ...
11997    66505.6
11998    23315.2
11999    66505.6
12000    76409.6
12001    70915.2
Name: annual_income, Length: 12002, dtype: float64

# 4. Filtering Data

Filtering allows you to retrieve only the rows that satisfy one or more conditions. It helps you focus on specific records for analysis without modifying the original dataset.

### Questions

1. Display all records where the **`gender`** is **'M'**.
2. Display all records where the **`age_of_driver`** is greater than **40**.
3. Display all records where the **`annual_income`** is greater than **50000**.
4. Display all records where the **`vehicle_category`** is **'Medium'**.
5. Display all records where the **`fraud reported`** is **'Y'**.
6. Display all records where the **`fraud reported`** is **'N'**.
7. Display all records where the **`past_num_of_claims`** is greater than **2**.
8. Display all records where the **`age_of_driver`** is between **25** and **40**.
9. Display all records where the **`annual_income`** is greater than **50000** and the **`gender`** is **'F'**.
10. Display all records where the **`vehicle_category`** is **'Medium'** or **'Large'**.
11. Display the first **10** records where the **`fraud reported`** is **'Y'**.

In [15]:
df[df["gender"] == "M"]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.278190,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.460210,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.385830,3014.110884,1000,1199.44,8.264032,3,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.979970,4064.569489,1000,1187.96,10.259629,2,N
6,1700352,50,M,1,89,62611.2,1,1,Rent,20151,...,Large,53451.421010,silver,7131.377201,5712.282494,2000,1104.50,8.588021,3,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11992,621561600,69,M,1,83,67748.8,1,1,Rent,50033,...,Compact,13391.566810,gray,15435.695540,3688.149479,500,1078.65,9.800262,3,N
11994,621644544,41,M,1,63,59409.6,1,0,Rent,15022,...,Medium,20732.814060,gray,48782.356790,2350.450424,500,1518.54,9.941920,1,N
11995,621665280,42,M,0,71,39832.0,0,1,Own,20113,...,Large,50804.103420,gray,12208.586220,2142.045782,2000,1239.06,9.748278,6,Y
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.534740,6639.049156,1000,1622.67,12.449888,3,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.844180,5236.564274,500,1232.57,9.116981,4,N

In [16]:
df[df["age_of_driver"] > 40]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.277720,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.979970,4064.569489,1000,1187.96,10.259629,2,N
5,1244160,42,F,0,68,29779.2,1,0,Own,80042,...,Medium,12689.884290,white,6535.967672,2812.365265,2000,972.18,9.443032,2,Y
6,1700352,50,M,1,89,62611.2,1,1,Rent,20151,...,Large,53451.421010,silver,7131.377201,5712.282494,2000,1104.50,8.588021,3,N
7,1804032,42,F,1,68,79776.0,1,0,Own,80015,...,Large,17740.699470,black,28271.743190,9218.58245,1000,1088.34,10.206506,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11994,621644544,41,M,1,63,59409.6,1,0,Rent,15022,...,Medium,20732.814060,gray,48782.356790,2350.450424,500,1518.54,9.941920,1,N
11995,621665280,42,M,0,71,39832.0,0,1,Own,20113,...,Large,50804.103420,gray,12208.586220,2142.045782,2000,1239.06,9.748278,6,Y
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.211040,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.879810,7475.901535,2000,1155.97,8.386094,2,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.844180,5236.564274,500,1232.57,9.116981,4,N

In [17]:
df[df["annual_income"] > 50000]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.278190,5196.552552,1000,1406.91,8.641800,5,N
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.385830,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.277720,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.979970,4064.569489,1000,1187.96,10.259629,2,N
6,1700352,50,M,1,89,62611.2,1,1,Rent,20151,...,Large,53451.421010,silver,7131.377201,5712.282494,2000,1104.50,8.588021,3,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11996,621706752,31,F,1,70,88593.6,0,1,Own,80004,...,Compact,43472.514050,white,19151.517500,3152.915424,2000,1246.68,10.644784,4,N
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.534740,6639.049156,1000,1622.67,12.449888,3,N
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.879810,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.919540,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.844180,5236.564274,500,1232.57,9.116981,4,N

In [18]:
df[df["vehicle_category"] == "Medium"]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.460210,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.385830,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.277720,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.979970,4064.569489,1000,1187.96,10.259629,2,N
5,1244160,42,F,0,68,29779.2,1,0,Own,80042,...,Medium,12689.884290,white,6535.967672,2812.365265,2000,972.18,9.443032,2,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11972,619923456,50,M,0,85,62604.8,1,0,Rent,50010,...,Medium,26628.702630,red,15577.071420,3009.515851,500,1518.54,9.734243,4,Y
11986,620960256,40,F,1,75,23315.2,1,1,Rent,80002,...,Medium,16087.300780,silver,21511.189110,2837.855285,1000,1324.78,7.558578,4,Y
11993,621603072,45,F,0,77,60884.8,0,1,Rent,50013,...,Medium,6625.618162,black,22682.932060,7833.945982,1000,1324.78,8.840455,6,N
11994,621644544,41,M,1,63,59409.6,1,0,Rent,15022,...,Medium,20732.814060,gray,48782.356790,2350.450424,500,1518.54,9.941920,1,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.844180,5236.564274,500,1232.57,9.116981,4,N

In [19]:
df[df["fraud reported"] == "Y"]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.35282,black,26707.460210,7957.267641,2000,1415.74,10.009761,5,Y
5,1244160,42,F,0,68,29779.2,1,0,Own,80042,...,Medium,12689.88429,white,6535.967672,2812.365265,2000,972.18,9.443032,2,Y
8,2135808,30,F,1,79,34419.0,1,1,Own,50041,...,Medium,28091.43192,silver,15488.987120,3973.694785,1000,988.45,7.041740,3,Y
11,2343168,28,F,1,49,53307.2,1,1,Rent,15057,...,Compact,23876.17436,silver,32074.034690,3456.679158,500,1737.66,10.667929,8,Y
13,2592000,42,F,0,92,39814.4,1,1,Own,50009,...,Compact,12006.56270,red,12427.001820,3388.568025,2000,1273.70,9.966160,4,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11986,620960256,40,F,1,75,23315.2,1,1,Rent,80002,...,Medium,16087.30078,silver,21511.189110,2837.855285,1000,1324.78,7.558578,4,Y
11990,621167616,59,M,0,63,65252.8,1,0,Own,80006,...,Compact,30786.60990,silver,36795.166830,3630.92594,500,1082.36,8.697555,3,Y
11991,621478656,46,M,1,97,31257.6,1,1,Own,15021,...,Large,32401.76839,silver,13635.226520,3885.037314,1000,1726.91,8.431915,3,Y
11995,621665280,42,M,0,71,39832.0,0,1,Own,20113,...,Large,50804.10342,gray,12208.586220,2142.045782,2000,1239.06,9.748278,6,Y
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.73927,gray,26718.211040,3382.4126,500,1055.60,9.730108,6,Y

In [20]:
df[df["fraud reported"] == "N"]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.278190,5196.552552,1000,1406.91,8.641800,5,N
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.385830,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.277720,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.979970,4064.569489,1000,1187.96,10.259629,2,N
6,1700352,50,M,1,89,62611.2,1,1,Rent,20151,...,Large,53451.421010,silver,7131.377201,5712.282494,2000,1104.50,8.588021,3,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11996,621706752,31,F,1,70,88593.6,0,1,Own,80004,...,Compact,43472.514050,white,19151.517500,3152.915424,2000,1246.68,10.644784,4,N
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.534740,6639.049156,1000,1622.67,12.449888,3,N
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.879810,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.919540,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.844180,5236.564274,500,1232.57,9.116981,4,N

In [21]:
df[df["past_num_of_claims"] > 2]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
22,4790016,42,F,1,65,179808.0,0,1,Rent,85072,...,Large,34221.325160,silver,21670.540250,4019.553749,2000,1514.72,10.205005,5,N
36,7547904,55,F,1,93,64113.6,1,1,Own,80002,...,Compact,32829.026680,blue,5747.298004,1882.484537,500,1398.51,8.835089,6,Y
52,10305792,48,M,1,94,80561.6,0,1,Rent,85067,...,Compact,25215.643300,white,17997.978620,4501.841953,500,1722.95,8.096151,2,N
69,13561344,27,F,1,69,52723.2,1,0,Own,80024,...,Compact,10073.112340,blue,19897.241910,4045.376399,2000,1035.79,8.579935,6,N
78,15303168,52,F,1,69,160162.0,0,0,Own,80013,...,Medium,17243.707390,white,45190.146190,3760.108962,500,947.75,8.786624,3,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11939,616709376,59,F,1,76,65244.8,1,1,Rent,80011,...,Large,21436.164680,gray,10750.243380,9146.552958,2000,1239.06,9.973206,2,Y
11956,618285312,42,F,1,59,70915.2,0,1,Rent,20138,...,Medium,52297.958010,black,26540.380530,6005.816586,2000,1155.97,11.621721,4,N
11964,619176960,49,F,1,42,62262.4,1,0,Rent,15042,...,Compact,18015.091890,other,16925.579900,5336.594213,500,1078.65,12.297336,5,Y
11981,620732160,59,M,1,79,65230.4,1,0,Rent,80006,...,Compact,4407.343178,silver,21398.125480,3260.030041,1000,999.43,8.599895,6,Y
11992,621561600,69,M,1,83,67748.8,1,1,Rent,50033,...,Compact,13391.566810,gray,15435.695540,3688.149479,500,1078.65,9.800262,3,N

In [22]:
df[(df["age_of_driver"] > 25) & (df["age_of_driver"] < 40)]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.59273,silver,26633.278190,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.35282,black,26707.460210,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.42523,gray,15279.385830,3014.110884,1000,1199.44,8.264032,3,N
8,2135808,30,F,1,79,34419.0,1,1,Own,50041,...,Medium,28091.43192,silver,15488.987120,3973.694785,1000,988.45,7.041740,3,Y
11,2343168,28,F,1,49,53307.2,1,1,Rent,15057,...,Compact,23876.17436,silver,32074.034690,3456.679158,500,1737.66,10.667929,8,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11979,620504064,32,F,1,89,23315.2,1,1,Rent,85074,...,Compact,11716.40420,silver,9807.598785,8972.021891,2000,1246.68,6.982758,2,Y
11980,620628480,37,F,1,76,57777.6,1,0,Rent,15057,...,Compact,14754.96816,white,23331.969130,10977.33315,500,1082.36,9.500880,7,Y
11996,621706752,31,F,1,70,88593.6,0,1,Own,80004,...,Compact,43472.51405,white,19151.517500,3152.915424,2000,1246.68,10.644784,4,N
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.33475,red,34516.534740,6639.049156,1000,1622.67,12.449888,3,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.03192,black,16122.919540,3838.951645,1000,1726.91,10.314865,5,N

In [23]:
df[(df["annual_income"] > 50000) & (df["gender"] == "F")]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
7,1804032,42,F,1,68,79776.0,1,0,Own,80015,...,Large,17740.699470,black,28271.74319,9218.58245,1000,1088.34,10.206506,2,N
9,2198016,49,F,0,57,62248.0,1,0,Own,80015,...,Large,23264.325310,blue,33770.80035,4264.395565,2000,1155.55,9.491945,5,N
11,2343168,28,F,1,49,53307.2,1,1,Rent,15057,...,Compact,23876.174360,silver,32074.03469,3456.679158,500,1737.66,10.667929,8,Y
16,3649536,44,F,0,65,160546.0,1,1,Rent,85001,...,Large,76566.413290,silver,30982.76488,10852.36645,500,1239.22,8.592965,3,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11988,621084672,40,F,0,91,59012.8,1,1,Own,20160,...,Large,31931.316140,white,19133.52963,4153.655544,2000,1239.06,9.214349,2,N
11993,621603072,45,F,0,77,60884.8,0,1,Rent,50013,...,Medium,6625.618162,black,22682.93206,7833.945982,1000,1324.78,8.840455,6,N
11996,621706752,31,F,1,70,88593.6,0,1,Own,80004,...,Compact,43472.514050,white,19151.51750,3152.915424,2000,1246.68,10.644784,4,N
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N

In [24]:
df[(df["vehicle_category"] == "Medium") | (df["vehicle_category"] == "Large")]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11994,621644544,41,M,1,63,59409.6,1,0,Rent,15022,...,Medium,20732.814060,gray,48782.35679,2350.450424,500,1518.54,9.941920,1,N
11995,621665280,42,M,0,71,39832.0,0,1,Own,20113,...,Large,50804.103420,gray,12208.58622,2142.045782,2000,1239.06,9.748278,6,Y
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N

In [25]:
df[df["fraud reported"] == "Y"].head(10)

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.460210,7957.267641,2000,1415.74,10.009761,5,Y
5,1244160,42,F,0,68,29779.2,1,0,Own,80042,...,Medium,12689.884290,white,6535.967672,2812.365265,2000,972.18,9.443032,2,Y
8,2135808,30,F,1,79,34419.0,1,1,Own,50041,...,Medium,28091.431920,silver,15488.987120,3973.694785,1000,988.45,7.041740,3,Y
11,2343168,28,F,1,49,53307.2,1,1,Rent,15057,...,Compact,23876.174360,silver,32074.034690,3456.679158,500,1737.66,10.667929,8,Y
13,2592000,42,F,0,92,39814.4,1,1,Own,50009,...,Compact,12006.562700,red,12427.001820,3388.568025,2000,1273.70,9.966160,4,Y
14,3525120,23,M,1,82,20164.8,1,0,Rent,15015,...,Compact,12224.550300,white,24375.062530,5335.459014,500,1848.81,9.411242,4,Y
15,3608064,55,M,1,83,14104.0,0,1,Own,80107,...,Compact,12845.131830,other,30130.722450,6011.22711,500,1362.87,8.528898,3,Y
17,3981312,37,F,0,68,7786.0,0,1,Rent,80022,...,Large,34708.882920,black,23599.396240,5904.032433,500,1105.49,8.546369,9,Y
21,4748544,27,M,0,36,32728.0,1,0,Rent,50023,...,Large,7879.238294,black,41443.382110,6794.780109,2000,769.95,9.057926,2,Y
24,5101056,34,M,1,82,16429.0,0,1,Own,20106,...,Large,20504.514370,black,44689.780430,3431.849274,2000,1136.83,8.164786,4,Y

# 5. Sorting Data

Sorting arranges the rows of a DataFrame in ascending or descending order based on one or more columns. It helps identify the highest, lowest, or ordered values in the dataset.

### Questions

1. Sort the DataFrame by **`vehicle_price`** in **descending order** and display the **top 10 records**.

2. Sort the DataFrame by **`vehicle_category`** in **ascending order**, and then by **`vehicle_price`** in **descending order**.

3. Display the **5 cheapest vehicles** based on the **`vehicle_price`** column.

4. Sort the DataFrame by **`annual_income`** in **ascending order** and display the **first 10 records**.

5. Sort the DataFrame by **`age_of_driver`** in **descending order** and display the **top 15 oldest drivers**.

In [26]:
df.sort_values("vehicle_price" , ascending=False).head(10)

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
7139,147515904,35,F,1,63,56875.2,1,0,Own,80027,...,Compact,106991.68450,blue,9744.901661,3502.41901,2000,1356.92,10.191684,8,N
3050,493765632,25,M,1,77,51532.8,1,1,Rent,20103,...,Compact,105849.19520,silver,25267.523770,5273.386495,2000,1155.97,10.061006,3,Y
2468,402589440,30,F,0,55,54412.8,1,1,Own,20159,...,Compact,97621.70110,gray,41427.068410,4438.061097,500,1232.57,9.874964,5,N
9724,401386752,41,M,1,38,59425.6,1,0,Own,50051,...,Medium,90948.30424,red,11769.159080,2862.807867,500,1055.60,10.467899,3,N
4965,390355200,35,M,1,79,56892.8,0,0,Rent,80033,...,Large,87777.09532,other,11669.684870,5567.886818,500,1082.36,3.889884,5,N
6357,70336512,47,F,1,75,92585.6,0,1,Rent,50023,...,Medium,86535.34070,red,22425.919980,7850.624107,500,722.66,11.605254,5,N
2681,433071360,59,F,1,62,65268.8,1,0,Rent,50048,...,Compact,86010.22326,blue,31268.401590,3624.91623,500,1082.36,9.712427,3,Y
9404,372231936,36,F,1,63,157334.4,1,1,Rent,20101,...,Medium,84898.64534,silver,44786.589550,4543.841184,2000,1155.97,7.214897,1,N
10471,476990208,43,F,1,94,60198.4,1,1,Own,85042,...,Compact,84680.32680,blue,41592.449970,5591.727243,500,1055.60,11.467154,4,N
1706,272947968,64,F,1,89,66524.8,1,0,Rent,80010,...,Medium,84417.55476,black,33227.674780,7119.333151,1000,1622.67,9.625175,1,N

In [27]:
df.sort_values(["vehicle_category" , "vehicle_price"] , ascending=[True , False])

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
7139,147515904,35,F,1,63,56875.2,1,0,Own,80027,...,Compact,106991.684500,blue,9744.901661,3502.41901,2000,1356.92,10.191684,8,N
3050,493765632,25,M,1,77,51532.8,1,1,Rent,20103,...,Compact,105849.195200,silver,25267.523770,5273.386495,2000,1155.97,10.061006,3,Y
2468,402589440,30,F,0,55,54412.8,1,1,Own,20159,...,Compact,97621.701100,gray,41427.068410,4438.061097,500,1232.57,9.874964,5,N
2681,433071360,59,F,1,62,65268.8,1,0,Rent,50048,...,Compact,86010.223260,blue,31268.401590,3624.91623,500,1082.36,9.712427,3,Y
10471,476990208,43,F,1,94,60198.4,1,1,Own,85042,...,Compact,84680.326800,blue,41592.449970,5591.727243,500,1055.60,11.467154,4,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9792,408312576,52,F,1,79,63211.2,1,1,Own,20142,...,Medium,3271.281696,white,37533.637020,6989.400258,1000,1622.67,11.531700,1,N
5422,545066496,53,F,1,56,63483.2,1,0,Own,85074,...,Medium,3231.936604,other,23219.899080,9515.803221,2000,1246.68,3.973406,5,N
4756,320557824,53,M,1,89,81241.6,1,1,Own,20164,...,Medium,3194.957820,other,29064.053020,3806.910689,2000,1155.97,4.157030,2,N
10874,514729728,35,M,1,83,56881.6,0,0,Own,15006,...,Medium,3073.101759,gray,26539.317340,7788.989525,500,1078.65,12.055416,1,N
6718,104820480,60,M,1,85,65510.4,1,1,Own,80023,...,Medium,3049.307756,blue,23607.247520,1321.932653,1000,766.19,9.677080,4,N

In [28]:
df.sort_values("vehicle_price" , ascending=False).head(5)

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
7139,147515904,35,F,1,63,56875.2,1,0,Own,80027,...,Compact,106991.68450,blue,9744.901661,3502.41901,2000,1356.92,10.191684,8,N
3050,493765632,25,M,1,77,51532.8,1,1,Rent,20103,...,Compact,105849.19520,silver,25267.523770,5273.386495,2000,1155.97,10.061006,3,Y
2468,402589440,30,F,0,55,54412.8,1,1,Own,20159,...,Compact,97621.70110,gray,41427.068410,4438.061097,500,1232.57,9.874964,5,N
9724,401386752,41,M,1,38,59425.6,1,0,Own,50051,...,Medium,90948.30424,red,11769.159080,2862.807867,500,1055.60,10.467899,3,N
4965,390355200,35,M,1,79,56892.8,0,0,Rent,80033,...,Large,87777.09532,other,11669.684870,5567.886818,500,1082.36,3.889884,5,N

In [29]:
df.sort_values("annual_income" , ascending=True).head(10)

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
4339,178806528,26,M,0,96,-1.6,0,0,Own,50006,...,Large,14487.47339,white,26846.78639,4077.993168,2000,1188.51,3.687944,6,N
321,54514944,38,M,1,79,-1.6,0,1,Own,50044,...,Medium,13231.61627,blue,11807.14132,9912.868738,1000,1361.45,8.248503,3,Y
5299,503967744,27,M,1,82,-1.6,1,1,Rent,85015,...,Compact,18065.93978,black,28550.69866,4284.790949,1000,999.43,4.607596,3,N
6860,118817280,32,M,0,49,-1.6,0,1,Rent,15022,...,Large,27550.16141,gray,16293.71651,4407.63998,500,1672.88,10.953477,3,N
9499,381189888,31,F,1,90,-1.6,0,0,Rent,15001,...,Large,15478.76923,gray,55684.29816,2678.258589,500,1055.60,7.984953,3,N
8510,285596928,40,M,1,68,-1.6,0,1,Rent,50026,...,Medium,15319.50591,red,13854.21894,6775.842276,1000,1324.78,12.092226,2,N
9336,365534208,48,F,1,92,-1.6,0,1,Own,50047,...,Medium,24636.26318,gray,11341.12605,5783.943551,500,1082.36,8.546133,2,N
9417,373496832,65,M,1,74,-1.0,1,0,Own,50032,...,Compact,17838.42956,gray,26389.29728,4513.692674,2000,1239.06,12.051301,9,N
5803,14411520,50,F,1,70,4585.6,1,1,Own,15031,...,Medium,17909.84344,other,18695.52643,2205.923814,1000,1348.32,9.989567,3,Y
17,3981312,37,F,0,68,7786.0,0,1,Rent,80022,...,Large,34708.88292,black,23599.39624,5904.032433,500,1105.49,8.546369,9,Y

In [30]:
df.sort_values("age_of_driver" , ascending=False).head(15)

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
7329,165867264,278,F,1,76,90040.0,1,0,Rent,80015,...,Large,7995.461039,black,19242.953210,10728.27333,1000,1361.45,9.831486,4,N
7542,186665472,249,M,1,94,88302.4,0,0,Own,80040,...,Compact,10785.663760,gray,35005.872680,6366.632672,500,722.66,9.162071,5,N
5644,1078272,180,F,1,87,83068.8,1,1,Own,20101,...,Medium,9223.388197,black,26935.007250,2678.252957,2000,1475.73,7.994253,7,N
5426,546600960,123,F,1,74,77017.6,1,0,Own,20132,...,Large,30392.900240,silver,19209.762010,1070.666244,500,1055.60,4.676576,8,N
7702,202652928,101,M,1,42,73854.4,0,0,Own,85023,...,Large,17169.837670,silver,12952.060830,4168.072078,500,1093.83,11.867458,4,Y
9039,336006144,100,M,1,78,73676.8,1,0,Own,15035,...,Compact,31033.818160,silver,31416.066230,5486.19417,2000,1239.06,10.058928,2,Y
5794,13934592,99,F,1,75,73542.4,1,1,Rent,20148,...,Medium,11971.103370,other,23507.143050,2177.815265,2000,1589.54,8.387788,7,N
821,132482304,96,M,0,47,73032.0,1,1,Own,80026,...,Compact,46225.965750,black,29498.333160,2605.219684,500,1672.88,9.530691,2,N
11120,539426304,93,F,1,86,72545.6,1,1,Rent,80014,...,Large,23360.610060,white,5832.261622,2353.342952,500,1518.54,11.199225,2,N
2062,331153920,93,M,1,71,72531.2,1,1,Rent,20136,...,Medium,26125.343580,silver,4933.992553,3322.272164,1000,1622.67,8.353155,3,Y
7858,217810944,93,F,1,76,72499.2,0,0,Own,50025,...,Medium,24917.888230,red,11772.715470,6821.151465,500,1533.71,11.228920,3,Y
1319,216276480,93,M,1,80,72497.6,0,1,Own,20164,...,Compact,47516.405810,silver,5170.822726,4198.442418,500,1564.43,8.217402,2,N
7405,173145600,92,M,1,85,72355.2,1,0,Own,85053,...,Medium,23418.157130,gray,12821.465960,2281.242661,1000,840.95,9.610290,3,Y
7330,165908736,92,M,1,52,72316.8,1,0,Own,85015,...,Medium,12263.357460,gray,11829.201830,9083.485255,2000,1188.51,9.460615,6,N
1718,275000832,89,M,1,17,71841.6,1,0,Rent,85076,...,Large,7846.895551,red,12173.542430,4532.053111,500,1518.54,7.733113,6,N

# 6. Value Counts

The `value_counts()` function is used to count the frequency of unique values in a column. It helps understand the distribution of categorical data and identify the most common values.

### Questions

1. Count the number of drivers belonging to each **`gender`**.

2. Count the number of vehicles in each **`vehicle_category`**.

3. Find the most common **`vehicle_color`** in the dataset.

4. Show the frequency distribution of the **`fraud reported`** column (including missing values, if any).

5. Count the number of records for each **`marital_status`**.

In [33]:
df["gender"].value_counts()

gender
M    6216
F    5786
Name: count, dtype: int64

In [34]:
df["vehicle_category"].value_counts()

vehicle_category
Compact    4033
Medium     3996
Large      3973
Name: count, dtype: int64

In [38]:
df["vehicle_color"].value_counts().head(1)

vehicle_color
red    1766
Name: count, dtype: int64

In [39]:
df["fraud reported"].value_counts()

fraud reported
N    9043
Y    2951
Name: count, dtype: int64

In [40]:
df["marital_status"].value_counts()

marital_status
1    8582
0    3418
*       2
Name: count, dtype: int64

# 7. Null Value Analysis

Null Value Analysis helps identify missing data in a dataset. Detecting and handling missing values is an important preprocessing step before performing data analysis or building machine learning models.

### Questions

1. Check whether the DataFrame contains any missing (null) values.

2. Count the number of missing values in each column.

3. Calculate the percentage of missing values for each column.

4. Display only the columns that contain one or more missing values.

In [56]:
df.isnull().sum().sum()

np.int64(8)

In [47]:
df.isnull().sum()

claim_number          0
age_of_driver         0
gender                0
marital_status        0
safety_rating         0
annual_income         0
high_education        0
address_change        0
property_status       0
zip_code              0
claim_date            0
claim_day_of_week     0
accident_site         0
past_num_of_claims    0
witness_present       0
liab_prct             0
channel               0
police_report         0
age_of_vehicle        0
vehicle_category      0
vehicle_price         0
vehicle_color         0
total_claim           0
injury_claim          0
policy deductible     0
annual premium        0
days open             0
form defects          0
fraud reported        8
dtype: int64

In [52]:
df.isnull().mean() * 100

claim_number          0.000000
age_of_driver         0.000000
gender                0.000000
marital_status        0.000000
safety_rating         0.000000
annual_income         0.000000
high_education        0.000000
address_change        0.000000
property_status       0.000000
zip_code              0.000000
claim_date            0.000000
claim_day_of_week     0.000000
accident_site         0.000000
past_num_of_claims    0.000000
witness_present       0.000000
liab_prct             0.000000
channel               0.000000
police_report         0.000000
age_of_vehicle        0.000000
vehicle_category      0.000000
vehicle_price         0.000000
vehicle_color         0.000000
total_claim           0.000000
injury_claim          0.000000
policy deductible     0.000000
annual premium        0.000000
days open             0.000000
form defects          0.000000
fraud reported        0.066656
dtype: float64

In [62]:
missing_cols = df.columns[df.isnull().any()]
print(missing_cols)

Index(['fraud reported'], dtype='object')